name: ios_fl_n_niagarafalls_3424
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.5.0
  share_plus: ^10.1.4
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.5.2
  font_awesome_flutter: ^10.8.0
  table_calendar: ^3.2.0
  image_picker: ^1.1.2
  just_audio: ^0.9.46
  url_launcher: ^6.3.1
  audio_waveforms: ^1.3.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/falls/
    - assets/images/games/
    - assets/waterfalls_sounds/
